# @package _group_
early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: 'val_loss'
    patience: 10
    mode: min
    min_delta: 1e-5
    verbose: True

checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: 'val_loss'
    save_top_k: 1
